/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Class.Clientes;
import java.util.ArrayList;
import java.util.Arrays;

/**
 *
 * @author Kendrick
 */
public class frmRegisterClientes extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmRegisterClientes.class.getName());

    /**
     * Creates new form frmRegisterClientes
     */
    public frmRegisterClientes() {
        initComponents();
        for (Clientes c : listaClientes) {
            taClientes.append(c.toString() + "\n");
        }
        txtSize.setText(" Total: " + listaClientes.size());
        txtId.requestFocus();

    }
    Clientes c = new Clientes();

//    private void cargarTabla() {
//        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
//        modelo.setRowCount(0); // limpiar tabla
//
//        for (Clientes cliente : listaClientes) {
//            Object[] fila = {
//                cliente.getId(),
//                cliente.getNombre(),
//                cliente.getTelefono(),
//                cliente.getCorreo(),
//                cliente.getDireccion()
//            };
//            modelo.addRow(fila); // 👈 esto faltaba
//        }
//    }
//    ARRAYS
    ArrayList<Clientes> listaClientes = new ArrayList<>(
            Arrays.asList(
                    new Clientes((byte) 56, "Joaquin Hernandez", 987653212, "jhernandez90@gmail.com", 51903829, "Av. Bolognesi 23"),
                    new Clientes((byte) 90, "Carla Pierola\t", 967532189, "carlapierola23@gmail.com", 23012938, "Jr. La union 90"),
                    new Clientes((byte) 2, "Jesus Carrasco", 906539213, "jesuscarr28@gmail.com", 41876390, "Calle 03 Los Jardines"),
                    new Clientes((byte) 30, "Maria Ramirez\t", 906765321, "mariaramirez2026@gmail.com", 80613829, "Av Colonia3"),
                    new Clientes((byte) 23, "Piero Quezada\t", 918080232, "quezadapiero26@gmail.com", 61906382, "AAHH Los Ejidos"),
                    new Clientes((byte) 90, "Jeanfranco Benavidez", 921362735, "jbenav06@gmail.com", 80729133, "Av Universitaria 234"),
                    new Clientes((byte) 18, "Antonio Sernaque", 906060239, "antonser21@gmail.com", 98032211, "AAHH DIVINO NIÑO")
            )
    );

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        iconHeadder = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDni = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        iconNuevo = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnNuevo = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        iconModificar = new javax.swing.JLabel();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        headertArea = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taClientes = new javax.swing.JTextArea();
        txtSize = new javax.swing.JTextField();
        aside = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registrar Clientes - Panel para administrar nuestros clientes");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setText("¡Registre los clientes!");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 23, -1, -1));

        iconHeadder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Group 8.png"))); // NOI18N
        jPanel2.add(iconHeadder, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 20, -1, -1));

        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Complete la informacion de sus clientes.");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel4.setText("ID Cliente *");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));
        jPanel2.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 112, 140, 30));

        jLabel5.setText("Documento Nacional de Identidad *");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, -1, -1));
        jPanel2.add(txtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 112, 180, 30));
        jPanel2.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 182, 140, 30));

        jLabel7.setText("Telefono *");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, -1, -1));
        jPanel2.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 180, 30));

        jLabel9.setText("Correo Electronico *");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));
        jPanel2.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 140, 30));

        jLabel10.setText("Direccion *");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, -1, -1));

        iconNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Group 62453.png"))); // NOI18N
        jPanel2.add(iconNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 50, 50));
        jPanel2.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 180, 30));
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 50, 50));

        jLabel6.setText("Nombres *");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        btnNuevo.setBackground(new java.awt.Color(0, 204, 0));
        btnNuevo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnNuevo.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevo.setText("Nuevo                        ");
        btnNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNuevo.setFocusCycleRoot(true);
        btnNuevo.setFocusTraversalPolicyProvider(true);
        btnNuevo.addActionListener(this::btnNuevoActionPerformed);
        jPanel2.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 150, 50));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Union.png"))); // NOI18N
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, 50, 50));

        btnGuardar.setBackground(new java.awt.Color(0, 102, 255));
        btnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar             ");
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.setFocusCycleRoot(true);
        btnGuardar.setFocusTraversalPolicyProvider(true);
        btnGuardar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnGuardarFocusLost(evt);
            }
        });
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);
        jPanel2.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 180, 50));

        iconModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Union2.png"))); // NOI18N
        jPanel2.add(iconModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 377, 50, 40));

        btnModificar.setBackground(new java.awt.Color(255, 255, 0));
        btnModificar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(153, 153, 153));
        btnModificar.setText("Modificar            ");
        btnModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModificar.setFocusCycleRoot(true);
        btnModificar.setFocusTraversalPolicyProvider(true);
        jPanel2.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 180, 50));

        btnEliminar.setBackground(new java.awt.Color(255, 0, 51));
        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar                 ");
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.setFocusCycleRoot(true);
        btnEliminar.setFocusTraversalPolicyProvider(true);
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);
        jPanel2.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, 50));

        jButton5.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton5.setText("<- Volver");
        jButton5.addActionListener(this::jButton5ActionPerformed);
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 450, 120, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 153));
        jLabel3.setText("_____________________________________________________________________________________________________________");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, -1, 30));

        headertArea.setBackground(new java.awt.Color(204, 255, 255));
        headertArea.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        headertArea.setForeground(new java.awt.Color(0, 153, 153));
        headertArea.setText("ID   |   NOMBRE          |    TELEFONO |  CORREO                                    |  DNI                           |  DIRECCION");
        jPanel2.add(headertArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 550, 20));

        taClientes.setEditable(false);
        taClientes.setColumns(20);
        taClientes.setRows(5);
        jScrollPane2.setViewportView(taClientes);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, 550, 320));

        txtSize.setEditable(false);
        txtSize.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        txtSize.setBorder(null);
        txtSize.addActionListener(this::txtSizeActionPerformed);
        jPanel2.add(txtSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 50, 60, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 1000, 500));

        aside.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aside.png"))); // NOI18N
        aside.setText("jLabel14");
        jPanel1.add(aside, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        Clientes newcliente = new Clientes();
        newcliente.setId(Byte.parseByte(txtId.getText()));
        newcliente.setNombre(txtNombre.getText());
        newcliente.setTelefono(Integer.parseInt(txtTelefono.getText()));
        newcliente.setCorreo(txtCorreo.getText());
        newcliente.setDni(Integer.parseInt(txtDni.getText()));
        newcliente.setDireccion(txtDireccion.getText());

        listaClientes.add(newcliente);
        taClientes.setText("");
        for (Clientes c : listaClientes) {
            taClientes.append(c.toString() + "\n");
        }

        txtSize.setText(" Total: " + listaClientes.size());
        txtId.setText("");
        txtNombre.setText("");
        txtTelefono.setText("");
        txtCorreo.setText("");
        txtDireccion.setText("");
        txtDni.setText("");
        txtId.requestFocus();
        javax.swing.JOptionPane.showMessageDialog(this, "Cliente Guardado exitosamente ✅");
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnGuardarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnGuardarFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarFocusLost

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSizeActionPerformed

    }//GEN-LAST:event_txtSizeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmRegisterClientes().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aside;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JLabel headertArea;
    private javax.swing.JLabel iconHeadder;
    private javax.swing.JLabel iconModificar;
    private javax.swing.JLabel iconNuevo;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea taClientes;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtSize;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
