/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Class.Celular;
import Class.Clientes;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Comparator;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Kendrick
 */
public class frmRegisterCelulares extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmRegisterCelulares.class.getName());

    /**
     * Creates new form frmRegisterCelulares
     */
    public frmRegisterCelulares() {
        initComponents();
        String[] estados = {"Pendiente", "En proceso", "Terminado"};
        comboEstado.setModel(new DefaultComboBoxModel<>(estados));
        comboEstado.setEnabled(false);

        taCelulares.setText("");
        for (Celular cel : listaCelulares) {
            taCelulares.append(cel.toString() + "\n");
        }
        txtSize.setText(" Total: " + listaCelulares.size());
        txtIdRegistro.requestFocus();

    }

    Celular cel = new Celular();

//    ARRAY CLIENTES PARA ACCEDER AL ID
    ArrayList<Clientes> listaClientes = new ArrayList<>(
            Arrays.asList(
                    new Clientes((byte) 56, "\tJoaquin Hernandez\t", 987653212, "\tjhernandez90@gmail.com\t", 51903829, "\tAv. Bolognesi 23"),
                    new Clientes((byte) 90, "\tCarla Pierola\t", 967532189, "\tcarlapierola23@gmail.com\t", 23012938, "\tJr. La union 90"),
                    new Clientes((byte) 2, "\tJesus Carrasco\t", 906539213, "\tjesuscarr28@gmail.com\t", 41876390, "\tCalle 03 Los Jardines"),
                    new Clientes((byte) 30, "\tMaria Ramirez\t", 906765321, "\tmariaramirez2026@gmail.com\t", 80613829, "\tAv Colonia3"),
                    new Clientes((byte) 23, "\tPiero Quezada\t", 918080232, "\tquezadapiero26@gmail.com\t", 61906382, "\tAAHH Los Ejidos"),
                    new Clientes((byte) 90, "\tJeanfranco Benavidez\t", 921362735, "\tjbenav06@gmail.com\t", 80729133, "\tAv Universitaria 234"),
                    new Clientes((byte) 18, "\tAntonio Sernaque\t", 906060239, "\tantonser21@gmail.com\t", 98032211, "\tAAHH DIVINO NIÑO")
            )
    );

    ArrayList<Celular> listaCelulares = new ArrayList<>(
            Arrays.asList(
                    new Celular((byte) 15, "\tAndroid\t", "\tSamsung\t", "\tGalaxy S23 Ultra\t", "\t582913740195632\t", (byte) 32, "\t12/07/2026\t", "\tPendiente"),
                    new Celular((byte) 2, "\tIOS\t", "\tApple\t", "\tiPhone 14 Pro\t\t", "\t903847561209384\t", (byte) 56, "\t12/07/2026\t", "\tPendiente"),
                    new Celular((byte) 3, "\tIOS\t", "\tApple\t", "\tiPhone 13\t\t", "\t174920583764910\t", (byte) 1, "\t12/07/2026\t", "\tPendiente"),
                    new Celular((byte) 4, "\tAndroid\t", "\tXiaomi\t", "\tRedmi Note 13\t\t", "\t665019283745601\t", (byte) 12, "\t12/07/2026\t", "\tPendiente"),
                    new Celular((byte) 17, "\tIOS\t", "\tApple\t", "\tiPhone 15\t\t", "\t318470592836174\t", (byte) 90, "\t12/07/2026\t", "\tPendiente"),
                    new Celular((byte) 16, "\tAndroid\t", "\tSamsung\t", "\tGalaxy A54\t\t", "\t759302184659273\t", (byte) 23, "\t12/07/2026\t", "\tPendiente"))
    );

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtIdRegistro = new javax.swing.JTextField();
        txtTipo = new javax.swing.JTextField();
        txtMarca = new javax.swing.JTextField();
        txtModelo = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtImei = new javax.swing.JTextField();
        txtCliente = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        btnNuevo = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        btnModificar = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taCelulares = new javax.swing.JTextArea();
        comboEstado = new javax.swing.JComboBox<>();
        headertArea = new javax.swing.JLabel();
        txtSize = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        btnOrdenar = new javax.swing.JButton();
        imgSearch = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        btnRecargar = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        btnClear = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registrar Celulares - Panel para administrar celulares de clientes");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("¡Registrar Celulares!");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Complete los campos y registre moviles a reparar");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel4.setText("ID Registro *");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel5.setText("Tipo *");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, -1, -1));

        jLabel6.setText("Marca *");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, -1, -1));

        jLabel7.setText("Modelo *");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel8.setText("IMEI *");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, -1, -1));

        jLabel9.setText("Cliente");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 40, 20));

        jLabel10.setText("Fecha de Registro *");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jLabel11.setText("Estado");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, -1, -1));
        jPanel1.add(txtIdRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 130, 30));
        jPanel1.add(txtTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 150, 30));
        jPanel1.add(txtMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 160, 30));
        jPanel1.add(txtModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 130, 30));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test 1.png"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 10, -1, -1));
        jPanel1.add(txtImei, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 150, 30));

        txtCliente.addActionListener(this::txtClienteActionPerformed);
        jPanel1.add(txtCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 150, 30));
        jPanel1.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 130, 30));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit.png"))); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 40, 50));

        btnNuevo.setBackground(new java.awt.Color(51, 255, 0));
        btnNuevo.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnNuevo.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevo.setText("Nuevo           ");
        btnNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNuevo.addActionListener(this::btnNuevoActionPerformed);
        jPanel1.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 130, 50));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/share.png"))); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 40, 50));

        btnGuardar.setBackground(new java.awt.Color(51, 153, 255));
        btnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar          ");
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 120, 50));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eye.png"))); // NOI18N
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, 40, 50));

        btnModificar.setBackground(new java.awt.Color(255, 204, 0));
        btnModificar.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(255, 255, 255));
        btnModificar.setText("Modificar          ");
        btnModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModificar.addActionListener(this::btnModificarActionPerformed);
        jPanel1.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 130, 50));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete.png"))); // NOI18N
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, -1, -1));

        btnEliminar.setBackground(new java.awt.Color(255, 0, 0));
        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar           ");
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 130, 60));

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton5.setText("<- Volver");
        jButton5.addActionListener(this::jButton5ActionPerformed);
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 450, -1, 30));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 153, 153));
        jLabel17.setText("______________________________________________________________________________________________");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, 540, 30));

        taCelulares.setEditable(false);
        taCelulares.setColumns(20);
        taCelulares.setRows(5);
        jScrollPane1.setViewportView(taCelulares);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, 470, 280));

        comboEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboEstado.addActionListener(this::comboEstadoActionPerformed);
        jPanel1.add(comboEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 150, 30));

        headertArea.setBackground(new java.awt.Color(204, 255, 255));
        headertArea.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        headertArea.setForeground(new java.awt.Color(0, 153, 153));
        headertArea.setText("ID   |   TIPO      |    MARCA  |  MODELO          |  IMEI    |  CLIENTE       |  FECHA  | ESTADO");
        jPanel1.add(headertArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, 480, 30));

        txtSize.setEditable(false);
        txtSize.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        txtSize.setBorder(null);
        txtSize.addActionListener(this::txtSizeActionPerformed);
        jPanel1.add(txtSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 70, 60, 30));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu.png"))); // NOI18N
        jLabel18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 70, 20, 30));

        btnOrdenar.setBackground(new java.awt.Color(204, 255, 204));
        btnOrdenar.setBorder(null);
        btnOrdenar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOrdenar.addActionListener(this::btnOrdenarActionPerformed);
        jPanel1.add(btnOrdenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 70, 40, 30));

        imgSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search-status.png"))); // NOI18N
        imgSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(imgSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 20, 50, 30));

        btnSearch.setBackground(new java.awt.Color(102, 102, 102));
        btnSearch.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        btnSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearch.addActionListener(this::btnSearchActionPerformed);
        jPanel1.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 20, 50, 30));

        txtSearch.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        txtSearch.addActionListener(this::txtSearchActionPerformed);
        jPanel1.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 320, 30));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/play-circle.png"))); // NOI18N
        jLabel19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 429, -1, 40));

        btnRecargar.setBackground(new java.awt.Color(0, 0, 255));
        btnRecargar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRecargar.addActionListener(this::btnRecargarActionPerformed);
        jPanel1.add(btnRecargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 430, 30, 40));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete-02.png"))); // NOI18N
        jLabel21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 430, -1, 40));

        btnClear.setBackground(new java.awt.Color(204, 0, 0));
        btnClear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClear.addActionListener(this::btnClearActionPerformed);
        jPanel1.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 430, 30, 40));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 1010, 500));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image 2.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1390, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void comboEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboEstadoActionPerformed
    }//GEN-LAST:event_comboEstadoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        Celular newcelular = new Celular();
        newcelular.setId(Byte.parseByte(txtIdRegistro.getText()));
        newcelular.setTipo(txtTipo.getText());
        newcelular.setMarca(txtMarca.getText());
        newcelular.setModelo(txtModelo.getText());
        newcelular.setImei(txtImei.getText());
        newcelular.setIdCliente(Byte.parseByte(txtCliente.getText()));
        newcelular.setEstado(comboEstado.getSelectedItem().toString());
        newcelular.setFechaIngreso(txtFecha.getText());
        listaCelulares.add(newcelular);
        taCelulares.setText("");
        for (Celular c : listaCelulares) {
            taCelulares.append(c.toString() + "\n");
        }
        txtSize.setText(" Total: " + listaCelulares.size());

        txtIdRegistro.setText("");
        txtTipo.setText("");
        txtMarca.setText("");
        txtModelo.setText("");
        txtImei.setText("");
        txtCliente.setText("");
        txtFecha.setText("");
        txtIdRegistro.requestFocus();
        javax.swing.JOptionPane.showMessageDialog(this, "Cliente Guardado exitosamente ✅");
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteActionPerformed
        String buscarcliente = txtCliente.getText();

        byte idBuscado = Byte.parseByte(buscarcliente);

        Clientes clienteEncontrado = new Clientes();
        for (Clientes c : listaClientes) {
            if (c.getId() == idBuscado) {
                clienteEncontrado = c;
                break;
            }
        }

        if (clienteEncontrado != null) {
            JOptionPane.showMessageDialog(this, "Cliente encontrado ✅\n" + "Nombre: " + clienteEncontrado.getNombre());
        } else {
            JOptionPane.showMessageDialog(this, "Cliente no existe ❌");
            txtCliente.setText("");
        }

    }//GEN-LAST:event_txtClienteActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        String celulareliminado = JOptionPane.showInputDialog("Ingrese el ID del celular eliminado.").trim();
        byte id = Byte.parseByte(celulareliminado);
        boolean eliminado = false;

        for (int i = 0; i < listaCelulares.size(); i++) {
            if (listaCelulares.get(i).getId() == id) {
                listaCelulares.remove(i);
                eliminado = true;
                break;
            }
        }
        if (eliminado) {
            JOptionPane.showMessageDialog(this, "CELULAR ELIMINADO CON EXITO");
            taCelulares.setText("");
            for (Celular ce : listaCelulares) {
                taCelulares.append(ce.toString() + "\n");
            }
        } else {
            JOptionPane.showMessageDialog(this, "NO SE ENCONTRO ID");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void txtSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSizeActionPerformed

    }//GEN-LAST:event_txtSizeActionPerformed

    private void btnOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenarActionPerformed
        taCelulares.setText("");

        listaCelulares.sort(Comparator.naturalOrder());
        for (Celular item : listaCelulares) {
            taCelulares.append(item.toString() + "\n");
        }

    }//GEN-LAST:event_btnOrdenarActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String searchCliente = txtSearch.getText().trim();

        taCelulares.setText("");
        boolean enc = false;

        for (Celular c : listaCelulares) {
            if (c.getMarca().trim().equalsIgnoreCase(searchCliente)) {
                taCelulares.append(c.toString() + "\n\n");
                enc = true;
            }
        }
        if (!enc) {
            JOptionPane.showMessageDialog(this, "No se encontro ningun celular");
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnRecargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecargarActionPerformed
        taCelulares.setText("");
        for (Celular c : listaCelulares) {
            taCelulares.append(c.toString() + "\n");
        }

        txtIdRegistro.requestFocus();

    }//GEN-LAST:event_btnRecargarActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        taCelulares.setText("");
        listaCelulares.clear();
        for (Celular rcel : listaCelulares) {
            taCelulares.append(rcel.toString());
        }
        JOptionPane.showMessageDialog(this, "Lista Eliminada con exito ✅");
    }//GEN-LAST:event_btnClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmRegisterCelulares().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnOrdenar;
    private javax.swing.JButton btnRecargar;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> comboEstado;
    private javax.swing.JLabel headertArea;
    private javax.swing.JLabel imgSearch;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea taCelulares;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtIdRegistro;
    private javax.swing.JTextField txtImei;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSize;
    private javax.swing.JTextField txtTipo;
    // End of variables declaration//GEN-END:variables
}
