/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Class.Celular;
import Class.Clientes;
import Class.Reparaciones;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Comparator;
import javax.swing.JOptionPane;

/**
 *
 * @author Kendrick
 */
public class frmRegisterReparaciones extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmRegisterReparaciones.class.getName());

    /**
     * Creates new form frmRegisterReparaciones
     */
    public frmRegisterReparaciones() {
        initComponents();

        for (Reparaciones rep : listaReparaciones) {
            taReparaciones.append(rep.toString() + "\n");
        }
        txtSize.setText("Total: " + listaReparaciones.size());

    }

//    ARRAYS DE CLIENTES Y CELULARES
    ArrayList<Clientes> listaClientes = new ArrayList<>(
            Arrays.asList(
                    new Clientes((byte) 56, "\tJoaquin Hernandez\t", 987653212, "\tjhernandez90@gmail.com\t", 51903829, "\tAv. Bolognesi 23"),
                    new Clientes((byte) 90, "\tCarla Pierola\t", 967532189, "\tcarlapierola23@gmail.com\t", 23012938, "\tJr. La union 90"),
                    new Clientes((byte) 2, "\tJesus Carrasco\t", 906539213, "\tjesuscarr28@gmail.com\t", 41876390, "\tCalle 03 Los Jardines"),
                    new Clientes((byte) 30, "\tMaria Ramirez\t", 906765321, "\tmariaramirez2026@gmail.com\t", 80613829, "\tAv Colonia3"),
                    new Clientes((byte) 23, "\tPiero Quezada\t", 918080232, "\tquezadapiero26@gmail.com\t", 61906382, "\tAAHH Los Ejidos"),
                    new Clientes((byte) 90, "\tJeanfranco Benavidez\t", 921362735, "\tjbenav06@gmail.com\t", 80729133, "\tAv Universitaria 234"),
                    new Clientes((byte) 18, "\tAntonio Sernaque\t", 906060239, "\tantonser21@gmail.com\t", 98032211, "\tAAHH DIVINO NIÑO")
            )
    );

    ArrayList<Celular> listaCelulares = new ArrayList<>(
            Arrays.asList(
                    new Celular((byte) 15, "\tAndroid\t", "\tSamsung\t", "\tGalaxy S23 Ultra\t", "\t582913740195632\t", (byte) 32, "\t12/07/2026\t", "\tPendiente"),
                    new Celular((byte) 2, "\tIOS\t", "\tApple\t", "\tiPhone 14 Pro\t\t", "\t903847561209384\t", (byte) 56, "\t12/07/2026\t", "\tPendiente"),
                    new Celular((byte) 3, "\tIOS\t", "\tApple\t", "\tiPhone 13\t\t", "\t174920583764910\t", (byte) 1, "\t12/07/2026\t", "\tPendiente"),
                    new Celular((byte) 4, "\tAndroid\t", "\tXiaomi\t", "\tRedmi Note 13\t\t", "\t665019283745601\t", (byte) 12, "\t12/07/2026\t", "\tPendiente"),
                    new Celular((byte) 17, "\tIOS\t", "\tApple\t", "\tiPhone 15\t\t", "\t318470592836174\t", (byte) 90, "\t12/07/2026\t", "\tPendiente"),
                    new Celular((byte) 16, "\tAndroid\t", "\tSamsung\t", "\tGalaxy A54\t\t", "\t759302184659273\t", (byte) 23, "\t12/07/2026\t", "\tPendiente"))
    );

    ArrayList<Reparaciones> listaReparaciones = new ArrayList<>(
            Arrays.asList(
                    new Reparaciones((byte) 11, (byte) 2, "Pantalla rota\t", "Cambio de display", 120.5, "12/07/2026", "14/07/2026", "Equipo con golpe fuerte", (byte) 1),
                    new Reparaciones((byte) 21, (byte) 3, "Bateria dañada\t", "Cambio de bateria", 80.0, "10/07/2026", "12/07/2026", "Se descarga rapido", (byte) 2),
                    new Reparaciones((byte) 32, (byte) 1, "No enciende\t", "Revision de placa", 150.0, "08/07/2026", "15/07/2026", "Posible corto circuito", (byte) 1),
                    new Reparaciones((byte) 04, (byte) 04, "Camara fallando", "Cambio de modulo", 95.5, "11/07/2026", "13/07/2026", "Imagen borrosa", (byte) 3),
                    new Reparaciones((byte) 25, (byte) 5, "Sin señal\t", "Reparacion de antena", 110.0, "09/07/2026", "16/07/2026", "No detecta red\t", (byte) 2),
                    new Reparaciones((byte) 16, (byte) 6, "Puerto dañado\t", "Cambio de puerto de carga", 70.0, "07/07/2026", "09/07/2026", "No carga correctamente", (byte) 1)            )
    );

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtIdCita = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtEquipo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtReparacion = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtDiagnostico = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtCosto = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtFechaInicio = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtFechaFin = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtTenico = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taReparaciones = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtSize = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        btnOrdenar = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registrar Reparaciones - Panel para administrar nuestras citas");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Group 85.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 160, 190));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image 3.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setText("¡Registre citas a nuestras citas!");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 23, -1, -1));

        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("Complete la informacion de sus clientes.");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel5.setText("ID Cita *");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));
        jPanel3.add(txtIdCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 112, 140, 30));

        jLabel6.setText("Equipo");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, -1, -1));
        jPanel3.add(txtEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 112, 180, 30));

        jLabel7.setText("Reparacion *");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, -1, -1));
        jPanel3.add(txtReparacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 180, 30));

        jLabel8.setText("Diagnostico *");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));
        jPanel3.add(txtDiagnostico, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 182, 140, 30));

        jLabel9.setText("Costo *");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));
        jPanel3.add(txtCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 140, 30));

        jLabel10.setText("Fecha Inicio *");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, -1, -1));
        jPanel3.add(txtFechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 180, 30));

        jLabel11.setText("Fecha Fin *");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));
        jPanel3.add(txtFechaFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 140, 30));

        jLabel12.setText("Descripcion *");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, -1, -1));

        txtDescripcion.addActionListener(this::txtDescripcionActionPerformed);
        jPanel3.add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 180, 30));

        jLabel13.setText("Tecnico *");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, 20));
        jPanel3.add(txtTenico, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 140, 30));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("jButton1");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, -1, -1));

        btnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);
        jPanel3.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, -1, -1));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setText("jButton3");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 450, -1, -1));

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setText("jButton4");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(this::jButton4ActionPerformed);
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, -1, -1));

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton5.setText("<- Volver");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 450, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 204, 204));
        jLabel15.setText("_____________________________________________________________________________________________________________________");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, -1, 20));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 204, 204));
        jLabel14.setText("ID | CELULAR | DIAGNOSTICO | REPARACION | COSTO | FECHA INICIO | FECHA FIN | DESCRIPCION | TECNICO");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 610, 10));

        taReparaciones.setEditable(false);
        taReparaciones.setColumns(20);
        taReparaciones.setRows(5);
        jScrollPane1.setViewportView(taReparaciones);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, 590, 260));

        jLabel16.setForeground(new java.awt.Color(255, 0, 51));
        jLabel16.setText("*");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 10, -1));

        jLabel17.setForeground(new java.awt.Color(255, 0, 51));
        jLabel17.setText("*");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 10, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hp.png"))); // NOI18N
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 0, -1, 100));

        txtSize.setEditable(false);
        txtSize.setBorder(null);
        jPanel3.add(txtSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 60, 70, 30));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu.png"))); // NOI18N
        jLabel19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 60, 30, 30));

        btnOrdenar.setBackground(new java.awt.Color(255, 255, 0));
        btnOrdenar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOrdenar.addActionListener(this::btnOrdenarActionPerformed);
        jPanel3.add(btnOrdenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 60, 40, 30));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search-status.png"))); // NOI18N
        jLabel21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 20, -1, 30));

        btnSearch.setBackground(new java.awt.Color(51, 51, 51));
        btnSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearch.addActionListener(this::btnSearchActionPerformed);
        jPanel3.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(682, 20, 60, 30));
        jPanel3.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 320, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 1020, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripcionActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        Reparaciones nuevaReparacion = new Reparaciones();
        nuevaReparacion.setId(Byte.parseByte(txtIdCita.getText()));
        nuevaReparacion.setIdCelular(Byte.parseByte(txtEquipo.getText()));
        nuevaReparacion.setDiagnostico(txtDiagnostico.getText());
        nuevaReparacion.setReparacion(txtReparacion.getText());
        nuevaReparacion.setCosto(Double.parseDouble(txtCosto.getText()));
        nuevaReparacion.setFechaInicio(txtFechaInicio.getText());
        nuevaReparacion.setFechaFin(txtFechaFin.getText());
        nuevaReparacion.setDescripcion(txtDescripcion.getText());
        nuevaReparacion.setTecnico(Byte.parseByte(txtTenico.getText()));
        listaReparaciones.add(nuevaReparacion);
        taReparaciones.setText("");
        for (Reparaciones r : listaReparaciones) {
            taReparaciones.append(r.toString() + "\n");
        }
        txtSize.setText("Total: " + listaReparaciones.size());

        txtIdCita.setText("");
        txtEquipo.setText("");
        txtCosto.setText("");
        txtDescripcion.setText("");
        txtDiagnostico.setText("");
        txtFechaFin.setText("");
        txtFechaInicio.setText("");
        txtReparacion.setText("");
        txtTenico.setText("");
        txtIdCita.requestFocus();
        JOptionPane.showMessageDialog(this, "Reparacion agregada con exito");

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenarActionPerformed
        taReparaciones.setText("");
        listaReparaciones.sort(Comparator.naturalOrder());
        
        for(Reparaciones rep:listaReparaciones){
            taReparaciones.append(rep.toString()+"\n");
        }
        txtIdCita.requestFocus();
        
        
    }//GEN-LAST:event_btnOrdenarActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String searchBuscado = txtSearch.getText().trim();
        
        taReparaciones.setText("");
        boolean encontrado = false;
        
        for(Reparaciones r : listaReparaciones){
            if(r.getFechaFin().trim().equalsIgnoreCase(searchBuscado)){
                taReparaciones.append(r.toString()+"\n");
                encontrado = true;
            }
        }
        if(!encontrado){
            JOptionPane.showMessageDialog(this, "Tecnico no encontrado");
        }
        
    }//GEN-LAST:event_btnSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmRegisterReparaciones().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnOrdenar;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea taReparaciones;
    private javax.swing.JTextField txtCosto;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtDiagnostico;
    private javax.swing.JTextField txtEquipo;
    private javax.swing.JTextField txtFechaFin;
    private javax.swing.JTextField txtFechaInicio;
    private javax.swing.JTextField txtIdCita;
    private javax.swing.JTextField txtReparacion;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSize;
    private javax.swing.JTextField txtTenico;
    // End of variables declaration//GEN-END:variables
}
